language: python
sudo: false

cache:
  directories:
    - eggs

matrix:
    include:

    - python: "2.7.16"
      env: 
       - PLONE_VERSION=4.3

    - python: "2.7.16"
      env: 
       - PLONE_VERSION=5.0

    - python: "2.7.16"
      env: 
       - PLONE_VERSION=5.1

    - python: "2.7.16"
      env: 
       - PLONE_VERSION=5.2

    - python: "3.6"
      env: 
       - PLONE_VERSION=5.2

install:
  - pip install -r requirements.txt
  - python --version
  - sed -ie "s#test-5.1.x.cfg#test-$PLONE_VERSION.x.cfg#" buildout.cfg
  - mkdir -p buildout-cache/downloads
  - buildout -c buildout.cfg -N -q -t 3
script: bin/test
