language: python
sudo: false
python:
  - 2.7
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
before_install:
  - virtualenv .
  - bin/pip install --upgrade pip setuptools zc.buildout
install:
  - bin/buildout -N -t 20
script:
  - bin/test
